version: '3'

services:
  # Yerel build ile çalıştırma
  news-local:
    build:
      context: .
      dockerfile: Dockerfile
    image: news-local
    container_name: news-local
    stdin_open: true  # Keep STDIN open
    tty: true         # Allocate a pseudo-TTY
    restart: "no"     # Don't restart automatically

  # Docker Hub'dan çekme
  news-dockerhub:
    image: furkandogmus/news:latest
    container_name: news-dockerhub
    stdin_open: true
    tty: true
    restart: "no"

  # GitHub Container Registry'den çekme
  news-github:
    image: ghcr.io/furkandogmus/haberlerplus:latest
    container_name: news-github
    stdin_open: true
    tty: true
    restart: "no"

  # Otomatik seçim ile çalıştırma (CNN Türk GÜNDEM)
  cnnturk-gundem:
    image: news-local
    container_name: news-cnnturk-gundem
    stdin_open: true
    tty: false
    restart: "no"
    command: sh -c "printf '6\n1\n' | news" 